import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import { getOptionalGroup } from "@/lib/clerk";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nextjs Clerk Prisma Template",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentGroup = await getOptionalGroup();
  
  return (
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ClerkProvider>
            <Navbar currentGroup={currentGroup}/>
            <div className="bg-gray-50 min-h-[calc(100vh-4rem)] flex flex-1">
              {children}
            </div>
            <Toaster />
          </ClerkProvider>
        </body>
      </html>
  );
}
